### PR TITLE
[MRG] Add eeg tests

### PR DESCRIPTION
**Pull request by sappelhoff**
this PR includes some overdue tests for the EEG part of the validator.

Mainly, this is bringing the EEG testing suite on par with MEG and iEEG.

### CODE REVIEW

**Comment by jasmainak** [comment]
isn't there a code coverage tool in javascript @chrisfilo ? I could find [istanbul-js](https://istanbul.js.org/) ...

**Comment by chrisgorgo** [comment]
There isn't - it might be worth opening a separate issue for it.

**Comment by sappelhoff** [comment]
>isn't there a code coverage tool in javascript @chrisfilo ? I could find istanbul-js ...
> >There isn't - it might be worth opening a separate issue for it.

A coverage tool would be helpful indeed. I'll open a separate issue. 

In the meanwhile, could you review this PR @jasmainak ?

**Comment by jasmainak** [comment]
PR looks reasonable to me @sappelhoff 

you should start paying me in beers next time you generate work for me ;-)

**Comment by sappelhoff** [comment]
Haha I certainly would ... if I did these PRs only for my personal pleasure 😀

@chrisfilo can you merge it?

**Pull request merged**
