### PR TITLE
Less verbose output when things are horribly wrong.

### PR DESCRIPTION
**Pull request by wtriplett**
Example:

```
./bin/bids-validator ~/Desktop/bids_dataset_wip --gentleSummary

        1: You have to define 'RepetitionTime' for this file. (code: 10)
                /sub-10150/func/sub-10150_task-rest_bold.nii.gz
                /sub-10150/func/sub-10150_task-scap_bold.nii.gz
                /sub-10150/func/sub-10150_task-stopsignal_bold.nii.gz
                /sub-10150/func/sub-10150_task-taskswitch_bold.nii.gz
                /sub-10159/func/sub-10159_task-bart_bold.nii.gz
                /sub-10159/func/sub-10159_task-rest_bold.nii.gz
                /sub-10159/func/sub-10159_task-scap_bold.nii.gz
                /sub-10159/func/sub-10159_task-stopsignal_bold.nii.gz
                /sub-10159/func/sub-10159_task-taskswitch_bold.nii.gz
                /sub-10171/func/sub-10171_task-bart_bold.nii.gz
                ... and 275 more files having this issue (--gentleSummary in effect).

        2: Not a valid JSON file. (code: 27)
                /sub-10150/anat/sub-10150_T1w.json
                        @ line: 2 character: 20
                        Evidence:         "ImageType": "ORIGINAL/PRIMARY/M/ND/NORM",
                /sub-10150/anat/sub-10150_T1w.json
                        @ line: 2 character: 20
                /sub-10150/beh/sub-10150_task-stopsignaltraining_beh.json
                        @ line: 2 character: 19
                        Evidence:       "task_params" : 
                /sub-10150/beh/sub-10150_task-stopsignaltraining_beh.json
                        @ line: 2 character: 19
                /sub-10150/dwi/sub-10150_dwi.json
                        @ line: 2 character: 20
                        Evidence:         "ImageType": "ORIGINAL/PRIMARY/M/ND/MOSAIC",
                /sub-10150/dwi/sub-10150_dwi.json
                        @ line: 2 character: 20
                /sub-10150/func/sub-10150_task-bart_bold.json
                        @ line: 2 character: 20
                        Evidence:         "ImageType": "ORIGINAL/PRIMARY/M/ND/MOSAIC",
                /sub-10150/func/sub-10150_task-bart_bold.json
                        @ line: 2 character: 20
                /sub-10150/func/sub-10150_task-rest_bold.json
                        @ line: 2 character: 20
                        Evidence:         "ImageType": "ORIGINAL/PRIMARY/M/ND/MOSAIC",
                /sub-10150/func/sub-10150_task-rest_bold.json
                        @ line: 2 character: 20
                ... and 1022 more files having this issue (--gentleSummary in effect).
```

### CODE REVIEW

**Comment by constellates** [comment]
This looks good to me and the output style is definitely helpful. I just tested on a datasets that had many of the same issues on ~180 different files and the gentle summary was much easier to read.

**Comment by chrisgorgo** [comment]
This seems quite useful. Maybe we should make it the default and point to "--verbose" for more details instead of adding a new flag.

**Comment by constellates** [comment]
> This seems quite useful. Maybe we should make it the default and point to "--verbose" for more details instead of adding a new flag.

I agree. This sounds like the way to go.

**Comment by wtriplett** [comment]
Sounds good to me too! Stay tuned for next commit...

**Comment by wtriplett** [comment]
Behavior is now:

```
./bin/bids-validator ~/Desktop/ds030_final

    1: You have to define 'RepetitionTime' for this file. (code: 10)
        /sub-10150/func/sub-10150_task-bart_bold.nii.gz
        /sub-10150/func/sub-10150_task-scap_bold.nii.gz
        /sub-10150/func/sub-10150_task-stopsignal_bold.nii.gz
        /sub-10150/func/sub-10150_task-rest_bold.nii.gz
        /sub-10150/func/sub-10150_task-taskswitch_bold.nii.gz
        /sub-10159/func/sub-10159_task-bart_bold.nii.gz
        /sub-10159/func/sub-10159_task-rest_bold.nii.gz
        /sub-10159/func/sub-10159_task-scap_bold.nii.gz
        /sub-10159/func/sub-10159_task-stopsignal_bold.nii.gz
        /sub-10159/func/sub-10159_task-taskswitch_bold.nii.gz
        ... and 2125 more files having this issue (Use --verbose to see them all).
```

With `--verbose`

```
    1: You have to define 'RepetitionTime' for this file. (code: 10)
        /sub-10150/func/sub-10150_task-bart_bold.nii.gz
            You have to define 'RepetitionTime' for this file. It can be included one of the following locations: /sub-10150/func/sub-10150_task-bart_bold.json, /sub-10150/sub-10150_task-bart_bold.json, /task-bart_bold.json
        /sub-10150/func/sub-10150_task-rest_bold.nii.gz
            You have to define 'RepetitionTime' for this file. It can be included one of the following locations: /sub-10150/func/sub-10150_task-rest_bold.json, /sub-10150/sub-10150_task-rest_bold.json, /task-rest_bold.json
        /sub-10150/func/sub-10150_task-stopsignal_bold.nii.gz
            You have to define 'RepetitionTime' for this file. It can be included one of the following locations: /sub-10150/func/sub-10150_task-stopsignal_bold.json, /sub-10150/sub-10150_task-stopsignal_bold.json, /task-stopsignal_bold.json
        /sub-10150/func/sub-10150_task-scap_bold.nii.gz
            You have to define 'RepetitionTime' for this file. It can be included one of the following locations: /sub-10150/func/sub-10150_task-scap_bold.json, /sub-10150/sub-10150_task-scap_bold.json, /task-scap_bold.json
        /sub-10150/func/sub-10150_task-taskswitch_bold.nii.gz
            You have to define 'RepetitionTime' for this file. It can be included one of the following locations: /sub-10150/func/sub-10150_task-taskswitch_bold.json, /sub-10150/sub-10150_task-taskswitch_bold.json, /task-taskswitch_bold.json
        /sub-10159/func/sub-10159_task-bart_bold.nii.gz
            You have to define 'RepetitionTime' for this file. It can be included one of the following locations: /sub-10159/func/sub-10159_task-bart_bold.json, /sub-10159/sub-10159_task-bart_bold.json, /task-bart_bold.json
        /sub-10159/func/sub-10159_task-rest_bold.nii.gz
            You have to define 'RepetitionTime' for this file. It can be included one of the following locations: /sub-10159/func/sub-10159_task-rest_bold.json, /sub-10159/sub-10159_task-rest_bold.json, /task-rest_bold.json
        /sub-10159/func/sub-10159_task-stopsignal_bold.nii.gz
[ ... output continues for all files ... ]
```

**Pull request merged**
