### PR TITLE
minimum value for part

### PR DESCRIPTION
**Pull request by teonbrooks**
`part` should be greater > 0

### CODE REVIEW

**Comment by jasmainak** [comment]
@teonbrooks can you add a test? ;-)

**Review by sappelhoff — CHANGES_REQUESTED** [review]
@teonbrooks by removing the 0 from the regexp, you also prevent it to detect numbers with leading zeros such as `run-01`. What you actually want to prevent is something like `run-0` or `run-0000`, right?

Fixing that will also make sure the tests pass again, see:

>   ● utils.type.file.isIEEG › isIEEG('/sub-01/ses-001/ieeg/sub-01_ses-001_task-rest_run-01_part-01_ieeg.edf') === true

**Comment by sappelhoff** [comment]
@teonbrooks do you have time to fix this?

**Comment by teonbrooks** [comment]
@sappelhoff unfortunately i don't have the time to fix this. feel free to take over

**Comment by sappelhoff** [comment]
Okay, no worries. I'll close it for now since there seems to be no substantially effortful changes in here.

In case this was driven by a user case that brought up a problem, it will hopefully come up again and can then be targeted by somebody else :-)

**Pull request closed without merging**
