### PR TITLE
fix: Use @libs/xml over xml2js for tiff parsing

### LINKED ISSUE #2105: xml2js is breaking the deno build
There's no winning with these dependencies.

> FYI I wanted to try it out and used the command as in https://github.com/bids-standard/bids-validator/issues/2081#issuecomment-2296830932 and got this error:
> ```
> docker run -ti --rm -v $PWD:/data:ro denoland/deno deno run --allow-read --allow-env --reload -A https://github.com/bids-standard/bids-validator/raw/deno-build/bids-validator.js /data
> error: Uncaught (in promise) Error: Dynamic require of "events" is not supported
>   throw Error('Dynamic require of "' + x + '" is not supported');
>         ^
>     at https://raw.githubusercontent.com/bids-standard/bids-validator/deno-build/bids-validator.js:12:9
>     at Object.<anonymous> (https://raw.githubusercontent.com/bids-standard/bids-validator/deno-build/bids-validator.js:11:12)
>     at ../../../../.cache/deno/deno_esbuild/xml2js@0.6.2/node_modules/xml2js/lib/parser.js (https://raw.githubusercontent.com/bids-standard/bids-validator/deno-build/bids-validator.js:395:4)
>     at __require3 (https://raw.githubusercontent.com/bids-standard/bids-validator/deno-build/bids-validator.js:15:50)
>     at Object.<anonymous> (https://raw.githubusercontent.com/bids-standard/bids-validator/deno-build/bids-validator.js:12:12)
>     at ../../../../.cache/deno/deno_esbuild/xml2js@0.6.2/node_modules/xml2js/lib/xml2js.js (https://raw.githubusercontent.com/bids-standard/bids-validator/deno-build/bids-validator.js:39:4)
>     at __require3 (https://raw.githubusercontent.com/bids-standard/bids-validator/deno-build/bids-validator.js:15:50)
>     at https://raw.githubusercontent.com/bids-standard/bids-validator/deno-build/bids-validator.js:6:25
> ```

_Originally posted by @mateuszpawlik in https://github.com/bids-standard/bids-validator/issues/2091#issuecomment-2304074851_

### PR DESCRIPTION
**Pull request by nellh**
This should work in browser builds too.

Resolves #2105

### CODE REVIEW

**Comment by nellh** [comment]
Working on potential fixes for the Vite issue still.

**Comment by rwblair** [comment]
My current ranking of preferred solutions is:
1. This #2106   - Better xml library, closest to original solution, most maintainable.
2. Chris' #2107 - Works, reduces dependencies. Unknown how robust it is for real world data.
3. Mine #2108 - Ugly as sin, most complex to maintain, but keeps og library in place.

@nellh You have any hope of there being a work around for the vite import:glob problem?

**Comment by nellh** [comment]
> @nellh You have any hope of there being a work around for the vite import:glob problem?

Narrowed this down to a bug in Vite itself, with the vite:asset-import-meta-url plugin. Added a small build plugin to patch the impacted code. I will try to get it fixed upstream but this should work in the meantime.

**Comment by nellh** [comment]
Vite upstream for this is here. https://github.com/vitejs/vite/issues/10597

**Pull request merged**
