### PR TITLE
gzipped fif files are not allowed

### PR DESCRIPTION
**Pull request by robertoostenveld**

### CODE REVIEW

**Comment by robertoostenveld** [comment]
see also https://github.com/bids-standard/bids-validator/issues/491

The gz compression is not done by the manufacturer. It breaks compatibility of the file format with their and other processing software.

**Comment by chrisgorgo** [comment]
Shouldn't the fif.gz extension be added to the spec first?

**Comment by robertoostenveld** [comment]
It was agreed with wide consensus that it should NOT be part of the spec. See 
https://github.com/bids-standard/bids-validator/issues/491#issuecomment-407100002

**Comment by chrisgorgo** [comment]
Sorry I misread the PR.

**Comment by robertoostenveld** [comment]
thanks

**Pull request merged**
