### PR TITLE
Executable

### PR DESCRIPTION
**Pull request by constellates**
Update for issue #103
- executables built on CI currently get stored as CI artifacts but are not automatically added as a github release.
- The appveyor config is setup but an appveyor account will need to be setup for the project.

### CODE REVIEW

**Comment by chrisgorgo** [comment]
This.Is.Amazing.

**Comment by chrisgorgo** [comment]
Would it possible to keep the executables under Releases? We can switch to using github tags instead of package.json version bumps to trigger a release.

**Comment by constellates** [comment]
Yea it's definitely possible to push these to releases. I put a link to a nice looking release tool in the related issue. I briefly tested it and it worked on my fork of the validator but there are some kinks to work out to get it working with circle-ci and appveyor and any race conditions between the two builds.

**Comment by nellh** [comment]
Closing this as stale.

**Pull request closed without merging**
