### PR TITLE
updated node version on CI

### PR DESCRIPTION
**Pull request by constellates**
Updated node in CI config to latest stable so newer gulp sass can be used on gh-pages.

### CODE REVIEW

**Comment by chrisgorgo** [comment]
What are the pros and cons of going to 5.6 instead of 4.3 LTS?

**Comment by constellates** [comment]
I guess it depends what we want to target support for, but LTS is probably what we should use. It's going to be slightly more stable, but more importantly more deployable based on various people's and organizations' policies.

The benefit of going newer is mainly that we've run into issues in the past with compatibility with v5 and newer and this would test against those.

**Comment by chrisgorgo** [comment]
Let's use 4.3 on circleCI. I got 5.6 on my machine and use it for testing. Unfortunately CircleCI does not support testing agains multiple node.js versions.

**Comment by constellates** [comment]
Sounds good.

**Pull request merged**
