### PR TITLE
ENH: Add physio/stim files to ASL and PET rules

### PR DESCRIPTION
**Pull request by effigies**
Added to the spec in https://github.com/bids-standard/bids-specification/pull/894

### CODE REVIEW

**Comment by marcelzwiers** [comment]
And pet as well?
```python
>>> bids_validator.BIDSValidator().is_bids('/sub-foo/pet/sub-foo_task_physio.json')
False
>>> bids_validator.BIDSValidator().is_bids('/sub-foo/pet/sub-foo_task_pet.json')
False

```

**Comment by marcelzwiers** [comment]
And pet as well?
```python
>>> bids_validator.BIDSValidator().is_bids('/sub-foo/pet/sub-foo_task-name_pet.json')
True
>>> bids_validator.BIDSValidator().is_bids('/sub-foo/pet/sub-foo_task-name_physio.json')
False
```

**Comment by effigies** [comment]
That's using this branch?

**Comment by marcelzwiers** [comment]
Sorry, I got some errors when I tried to install this branch and didn't test it. I just wanted to add the pet example so you could easily test it yourself if you wanted to. I suppose your PR fixes it

**Comment by effigies** [comment]
Gotcha. I did test your string and it passes.

**Review by sappelhoff — APPROVED** [review]

**Pull request merged**
