### PR TITLE
Improve readDir tests and fix harmonizeRelativePath for Windows

### PR DESCRIPTION
**Pull request by nellh**
This adds some additional test coverage and documentation for readDir to cover some cases which may affect Windows behavior and fixes a few small bugs in the test suite (extra console logging).

### CODE REVIEW

**Review by rwblair — APPROVED** [review]

**Comment by rwblair** [comment]
@sappelhoff can you try this branch to confirm it fixes issues on your end?

**Comment by sappelhoff** [comment]
Unfortunately it does not yet fix things: https://github.com/mne-tools/mne-bids/pull/254

See the Appveyor Log

This is how I install @nellh's branch:

image

**Comment by rwblair** [comment]
Just tested on a windows 10 VM using 10.16.1 against ds000005 and am seeing the same issue. Confirmed that it worked on linux w/10.16.1.

**Comment by nellh** [comment]
I'm going to merge this and open one more PR with a fix for #814

**Pull request merged**
