### PR TITLE
Support for BIDS 1.0.0-rc1

### PR DESCRIPTION
**Pull request by chrisgorgo**
This PR adds a set of tests based on example datasets and modifies the software to successfully validate them.

### CODE REVIEW

**Comment by chrisgorgo** [comment]
This is ready for review.

**Comment by constellates** [comment]
Thanks Chris. Everything looks good, I was just about to pull and test it and merge.

**Comment by constellates** [comment]
And then I'll bump the version and publish it. We're still below an initial release candidate version. Do you think this qualifies as a tentative 1.0 release or should we give it a little more time?

**Comment by chrisgorgo** [comment]
I am planning extending the validation process. Right now it barely
scratching the surfaces of all the constraints outlined in the
specification.

To begin with I will add a warning for every file that is not in the spec.
I'll send a PR soon.

**Pull request merged**
