### PR TITLE
Revert "remove isCorrectModality function and its call in quicktest"

### PR DESCRIPTION
**Pull request by effigies**
Reverts bids-standard/bids-validator#1122

Does not need to be merged, but I think it should be decided on before a release.

### CODE REVIEW

**Comment by sappelhoff** [comment]
@all-contributors please add @effigies  for code ideas infra question review

**Comment by sappelhoff** [comment]
2nd try 

@all-contributors please add @effigies for code ideas infra question review

**Comment by effigies** [comment]
@rwblair Should we restore this?

**Comment by rwblair** [comment]
Haven't been any issues with having removed that part of quicktest so far. Closing for now.

**Pull request closed without merging**
