### PR TITLE
MAINT: Add Python deployment to CircleCI

### LINKED ISSUE #684: Deploy to PyPI on release
We need to deploy to PyPI on release; this is currently keeping us from using this package in pybids (instead, we're currently using hard-copied versions of the rules from a few months ago). @effigies, any chance you could help us with this? It will probably take me a lot longer than it would take you...

### PR DESCRIPTION
**Pull request by effigies**
Fixes #684.

### CODE REVIEW

**Comment by effigies** [comment]
We'll need to add the appropriate environment variables for a PyPI push to Circle.

**Comment by jasmainak** [comment]
would this not also need tests before deploying to pypi?

**Comment by effigies** [comment]
Thanks for the reminder.

**Comment by effigies** [comment]
Somebody who is an owner of this repository should add PyPI credentials in the `TWINE_USERNAME` and `TWINE_PASSWORD` environment variables on CircleCI.

**Comment by effigies** [comment]
And depending on how conservative you are about new releases, you may want to test this functionality with a pre-release tag.

**Comment by chrisgorgo** [comment]
I granted you admin rights to this repo - please let me know if you have access to the relevant circleci config parameters.

**Comment by effigies** [comment]
I think I may need to be a bids-standard organization owner to do that on Circle. Either that or permissions take a while to sync.

**Comment by effigies** [comment]
Oh, nevermind. I found the correct settings page. Or maybe was suddenly granted access. Who knows!

**Comment by effigies** [comment]
Okay, environment variables are set. This is ready for review.

**Pull request merged**
