### PR TITLE
Rohan patch1

### PR DESCRIPTION
**Pull request by SetCodesToFire**
1st fix) #392

### CODE REVIEW

**Comment by SetCodesToFire** [comment]
2nd fix) #347

**Comment by SetCodesToFire** [comment]
3rd fix) #357

**Comment by SetCodesToFire** [comment]
Closing the pull requests #411 and #412 , because the changes done there are reflected in this new PR

**Comment by chrisgorgo** [comment]
Please provide one pull request per fix. This will speed up review process since PRs can be merged indepently.

**Comment by SetCodesToFire** [comment]
Okay. I will do them just now. Thanks 😄

**Comment by SetCodesToFire** [comment]
Closing this PR. Scattered this PR into three new PR #417  #416 #415

**Pull request closed without merging**
