### PR TITLE
Async error

### LINKED ISSUE #320: RangeError: Maximum call stack size exceeded for ds201
```
/scratch/04275/suyashdb/bids-validator/node_modules/async/dist/async.js:888
        return i < len ? {value: obj[key], key: key} : null;
                         ^

RangeError: Maximum call stack size exceeded
    at next (/scratch/04275/suyashdb/bids-validator/node_modules/async/dist/async.js:888:26)
    at replenish (/scratch/04275/suyashdb/bids-validator/node_modules/async/dist/async.js:937:28)
    at iterateeCallback (/scratch/04275/suyashdb/bids-validator/node_modules/async/dist/async.js:931:17)
    at /scratch/04275/suyashdb/bids-validator/node_modules/async/dist/async.js:906:16
    at NIFTI.async.eachOfLimit.issues.push.Issue.file (/scratch/04275/suyashdb/bids-validator/validators/nii.js:222:21)
    at replenish (/scratch/04275/suyashdb/bids-validator/node_modules/async/dist/async.js:946:17)
    at iterateeCallback (/scratch/04275/suyashdb/bids-validator/node_modules/async/dist/async.js:931:17)
    at /scratch/04275/suyashdb/bids-validator/node_modules/async/dist/async.js:906:16
    at NIFTI.async.eachOfLimit.issues.push.Issue.file (/scratch/04275/suyashdb/bids-validator/validators/nii.js:222:21)
    at replenish (/scratch/04275/suyashdb/bids-validator/node_modules/async/dist/async.js:946:17)
```

### PR DESCRIPTION
**Pull request by suyashdb**
closes #320

### CODE REVIEW

**Comment by chrisgorgo** [comment]
I think you accidentally added .idea folder

**Comment by suyashdb** [comment]
Ready to be merged.

**Comment by chrisgorgo** [comment]
Could you merge master or rebase?

**Comment by suyashdb** [comment]
I guess i don't have permission to merge in INCF master.

**Comment by chrisgorgo** [comment]
I meant merge INCF/master into your feature branch to update it.

**Comment by suyashdb** [comment]
ready for review.

**Pull request merged**
