### PR TITLE
[FIX] fixes submodule autoupdate

### PR DESCRIPTION
**Pull request by Remi-Gau**
a simpler but less flexible version that will update ALL submodules.

### CODE REVIEW

**Comment by sappelhoff** [comment]
Thanks for the quick fix!

**Comment by Remi-Gau** [comment]
> Thanks for the quick fix!

Well let's see how this thing behaves in the real world before shouting "victory"

**Comment by Remi-Gau** [comment]
do you want me to make the workflow run on PRs so we can test is here before merging?

**Comment by sappelhoff** [comment]
I am actually quite hopeful, having seen this work on your fork now :thinking:

**Comment by sappelhoff** [comment]
:tada: https://github.com/bids-standard/bids-validator/runs/6915881661?check_suite_focus=true

**Comment by Remi-Gau** [comment]
> I am actually quite hopeful, having seen this work on your fork now thinking

famous last words!

**Comment by Remi-Gau** [comment]
and "boom" here is your automatic submodule update delivery 'brought to you by github actions'

https://github.com/bids-standard/bids-validator/pull/1470

**Comment by Remi-Gau** [comment]
OK now doing the same with pybids

**Pull request merged**
