### PR TITLE
Skip session checks

### PR DESCRIPTION
**Pull request by rwblair**
On datasets with large numbers of subjects/sessions performing this check can cause the stack limit to be hit. Adding a flag to skip the checks can allow validation to complete for some datasets: #1083

### CODE REVIEW

**Comment by rwblair** [comment]
@sappelhoff any objection to adding this flag to allow skipping checks that generate these two warnings:
https://github.com/bids-standard/bids-validator/blob/556e86dff6e3b97249f3741bf76a8c5879d667ea/bids-validator/utils/issues/list.js#L207
https://github.com/bids-standard/bids-validator/blob/556e86dff6e3b97249f3741bf76a8c5879d667ea/bids-validator/utils/issues/list.js#L541

**Review by sappelhoff — APPROVED** [review]
no objections. it seems to be helpful for people who want to validate a massive amount of data at once 👍 

thanks for preparing it

**Comment by effigies** [comment]
Does this add a checkbox for the online validator?

**Comment by rwblair** [comment]
@effigies good catch, added.

**Pull request merged**
