### PR TITLE
expose colored/formatted console output in issues and summary

### PR DESCRIPTION
**Pull request by david-nishi**
#715

### CODE REVIEW

**Comment by olgn** [comment]
works great - to clarify this change, the prettified console output is now stored as an additional field on the callback from `validate.BIDS`. `validate.BIDS` callsback with an `(issues, summary)` pair. 

* prettier issue formatting is stored in `issues.consoleOutput`
* prettier summary formatting is stored in `summary.consoleOutput`.

openneuro can now provide this pretty output by accessing these fields in the validation callback and feeding them to `console.log`  

@DaNish808 needs to be rebased but then it's ready to merge

**Comment by nellh** [comment]
It would be more general to decouple the formatting from the validate function. This way you would have something like `validate.BIDS() => callback(issues, summary) => { formatIssues(issues), formatSummary(summary)}` which allows for those to be recomposed without changing validate.BIDS

**Comment by olgn** [comment]
@nellh good point

**Review by nellh — APPROVED** [review]
Nice, thanks for making the decoupling changes, this should make it easier to use this in openneuro-cli.

**Pull request merged**
