### PR TITLE
[ENH] Microscopy: Add validation of JSON for photo files

### PR DESCRIPTION
**Pull request by mariehbourget**
This PR adds validation of the new JSON file associated with microscopy photo files in:

- https://github.com/bids-standard/bids-specification/pull/1000.

Still WIP as the spec PR is not approved yet.

The new JSON file includes the `IntendedFor` field.
I used the same error code (`37`) and validation steps as in `nii.js` [here](https://github.com/bids-standard/bids-validator/blob/4feb91b8aa9506c123d38327485dd5d4cd69e80b/bids-validator/validators/nifti/nii.js#L1307).

New photos and associated JSON files are added in microscopy examples in:

- https://github.com/bids-standard/bids-examples/pull/307.

### CODE REVIEW

**Comment by rwblair** [comment]
These changes look good. I'm looking at a way to combine the logic from different parts of the validator. I'll update this PR accordingly depending on what I find.

**Comment by mariehbourget** [comment]
Hi @rwblair, is there any news on this PR?
Thanks!

**Comment by rwblair** [comment]
@mariehbourget  I made a PR against this branch:
https://github.com/neuropoly/bids-validator/pull/8

Adds some tests and rebases on master. I also tested against the bids-examples branch and it worked as expected.Once tests are passing for this I'll go ahead and merge it.

**Comment by mariehbourget** [comment]
Thanks @rwblair!
Just to make sure I understand correctly, you need me to merge https://github.com/neuropoly/bids-validator/pull/8 first?

As for merging to the bids-validator master, we may want to wait for https://github.com/bids-standard/bids-specification/pull/1000 to be approved, I'll ask for a final review.

**Comment by rwblair** [comment]
> Just to make sure I understand correctly, you need me to merge [neuropoly#8](https://github.com/neuropoly/bids-validator/pull/8) first?

That be great, depending on how the CI does I may make more PRs.

Waiting for the specification merge to happen first isn't a problem.

**Comment by mariehbourget** [comment]
Hi @rwblair!
I merged the [PR](https://github.com/neuropoly/bids-validator/pull/8) (neuropoly 8) and the specification PR https://github.com/bids-standard/bids-specification/pull/1000 was approved last week, so I think we are OK to proceed.

There are some errors with the last merge that I don't fully understand, let me know if there is anything I can do to help.
Thanks!

**Comment by sappelhoff** [comment]
@mariehbourget is the box "allow commits from maintainers" not checked? I just wanted to push a fix but couldn't do it.

Anyhow, fixes are in https://github.com/neuropoly/bids-validator/pull/9, which you can simply merge :-) --> but in the future it would be nice to tick the "allow commits from maintainers" box

**Review by sappelhoff — APPROVED** [review]

**Comment by mariehbourget** [comment]
> Anyhow, fixes are in [neuropoly#9](https://github.com/neuropoly/bids-validator/pull/9), which you can simply merge :-) --> but in the future it would be nice to tick the "allow commits from maintainers" box

Hi @sappelhoff, thanks for the PR [neuropoly#9](https://github.com/neuropoly/bids-validator/pull/9), it is now merged.

I would gladly grant you access of course but I could not find the "allow commits from maintainers" box anywhere, sorry about that. Is it supposed to be on the main page of the PR (this page)?

**Comment by sappelhoff** [comment]
see the lower right of this screenshot: 
image


or simply: Open a pull request of yours and search for "Allow edits and access to secrets by maintainers" or subsets of this string (just via ctrl+F search in your browser)

**Comment by mariehbourget** [comment]
Hum, that's what I thought from the github help pages but I have nothing under the "participants":

image

I'll keep looking and check if there is something in our fork settings.

**Comment by sappelhoff** [comment]
Yes, perhaps it's because you submitted the PR from a "third party" organization account :thinking: ... either the situation there is completely different OR you have insufficient rights there :man_shrugging: anyhow the solution is probably to next time do a PR from you personal fork :-)

**Pull request merged**
