### PR TITLE
Preliminary support for JSON Schema validation.

### PR DESCRIPTION
**Pull request by chrisgorgo**

### CODE REVIEW

**Comment by constellates** [comment]
Aside from the CI test failure and a version bump this looks good to me. The one thing I'm slightly unsure of is the conditional loading of schemas. Require statements work a little differently in the browser. I think the conditional loading should still be fine, but I would test that in the browser version to be sure.

**Comment by chrisgorgo** [comment]
I'm having problems building it locally, but I think it should work: http://stackoverflow.com/questions/23249826/browserify-nested-conditional-requires

**Comment by chrisgorgo** [comment]
This is how the output looks:

```
$ bin/bids-validator /d/example_artifacts_dataset/best_subset/
        1: JSON file is not formatted according the the schema. (code: 55 - JSON Schema validation error)
                /task-Beast_bold.json
                        Evidence: .SliceTiming should be array
                /task-Beast_sbref.json
                        Evidence: .SliceTiming should be array
                /task-epi_bold.json
                        Evidence: .SliceTiming should be array
                /task-rest_bold.json
                        Evidence: .SliceTiming should be array
                /task-reward_bold.json
                        Evidence: .SliceTiming should be array
                /task-reward_sbref.json
                        Evidence: .SliceTiming should be array
```

**Comment by chrisgorgo** [comment]
Fixes #245

**Pull request merged**
