### PR TITLE
make InstitutionalDepartmentName available for all datatypes

### LINKED ISSUE #1310: eeg, meg json schema include `InstitutionalDepartmentName` but the spec does not
see here:
- https://github.com/bids-standard/bids-validator/blob/39922c4159688fcc67ba6b723d391991c75211e3/bids-validator/validators/json/schemas/eeg.json#L10
- https://github.com/bids-standard/bids-validator/blob/39922c4159688fcc67ba6b723d391991c75211e3/bids-validator/validators/json/schemas/meg.json#L10

I think this is only used for MRI data in the spec:

https://github.com/bids-standard/bids-specification/blob/master/src/04-modality-specific-files/01-magnetic-resonance-imaging-data.md#institution-information

and this seems to keep in line with a dicom tag

https://github.com/bids-standard/bids-specification/blob/master/src/schema/metadata/InstitutionalDepartmentName.yaml

My gut feeling is to remove it from the json schema in the validator rather than modify the spec to align with the validator. But I may be missing something.

### PR DESCRIPTION
**Pull request by Remi-Gau**
fixes #1310 

# to do 

- [x] update beh.json schema to also contain InstitutionalDepartmentName

### CODE REVIEW

**Review by sappelhoff — COMMENTED** [review]
:| apparently there is at least one dataset in BIDS-examples that makes use of this field: https://github.com/bids-standard/bids-examples/blob/89211d4afc5ee3effee3d7fd4b093e1eaf15837f/eeg_rishikesh/sub-001/ses-01/eeg/sub-001_ses-01_task-meditation_eeg.json#L4

So despite what I said earlier, maybe it's more elegant to add this metadata to EEG and MEG in the spec, rather than removing it from the validator and breaking existing datasets?

I feel like this metadata could be interesting for some datasets 🤷‍♂️  it's not completely irrelevant at least.

WDYT?

**Comment by Remi-Gau** [comment]
Then I'd be of the opinion to make this a piece of metadata that we put in "common definitions" and that we make available for all data types.

This would mean updating the spec for iEEG, EEG, MEG, PET, behavior.

I care more mostly about internal consistency #DataOCD

**Comment by Remi-Gau** [comment]
I would suggest to bring the spec up to speed before we merge this one.

**Comment by Remi-Gau** [comment]
Will update the beh.json once #1311 is merged

**Comment by Remi-Gau** [comment]
@sappelhoff 
Also updated the behavior schema so all the required changes should be there.

**Review by sappelhoff — APPROVED** [review]
wonderful, thanks!

**Pull request merged**
