### PR TITLE
Fix typo found by codespell

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**

### CODE REVIEW

**Comment by effigies** [comment]
I'm curious why this wasn't found by our codespell action. I also can't find it locally. How did you run codespell to find this?

**Comment by Remi-Gau** [comment]
maybe worth having a codespell config in the repo rather than just define it in the GHA workflow.

**Comment by effigies** [comment]
Agreed, but it would be nice to know the configuration needed to detect this.

**Comment by DimitriPapadopoulos** [comment]
Oh, it's just that I'm using the latest dictionaries (I am currently merging many updates into the dictionaries).

**Pull request merged**
