### PR TITLE
Add regexps for space entity: EEG and iEEG

### LINKED ISSUE #743: `space` filename keyword is not restricted to the controlled vocabulary
See https://github.com/bids-standard/bids-validator/blob/2dab5a40bf38292bf91a1bedeb4dfddfe0d06b05/bids-validator/bids_validator/rules/file_level_rules.json#L174

My reading of the spec is that the allowed values are:

- Other
- Pixels
- ACPC
- MNI152Lin
- MNI152NLin6[Sym\|Asym]
- MNI152NLin2009[a-c][Sym\|Asym]
- MNIColin27
- MNI305 
- NIHPD
- Talairach
- OASIS30AntsOASISAnts
- OASIS30Atropos
- ICBM452AirSpace
- ICBM452Warp5Space
- IXI549Space
- fsaverage[3\|4\|5\|6\|sym]
- UNCInfant[0\|1\|2]V[21\|22\|23]

Related to https://neurostars.org/t/questions-about-appendix-viii-preferred-names-of-coordinate-systems/3758. Pinging @dorahermes and @choldgraf for confirmation

### LINKED ISSUE #1164: test bids-examples as part of bids-validator CI
the bids-examples CI should probably be run also as part of the bids-validator CI to see early when validator changes break examples. 

https://github.com/bids-standard/bids-examples/blob/a3135a66987841c42023c20d28b0e676855c3cce/.github/workflows/validate_datasets.yml#L1

The bids-examples are already included as a git submodule, but not testet:

https://github.com/bids-standard/bids-validator/tree/master/bids-validator/tests/data

### PR DESCRIPTION
**Pull request by adam2392**
Closes: #743 
closes #1164 

Adding regex pattern for iEEG space entity. 

## TODO
- [ ] ~~Add regex for MEG~~ space not in their entities currently, although probably would be applicable (headshape + markers)?
- [x] Add regex for EEG
- [x] Update unit tests
 
## Questions
- [x] How does one include the optional fields like ``MNI152NLin2009[a-c][Sym|Asym]`` (a-c and Sym/Asym) in regex?
- [x] Anyone have an idea where the tests are to fix for this PR?

### CODE REVIEW

**Comment by sappelhoff** [comment]
I think tests are not in place yet for the space entity :grimacing: 

this would be a proper place: https://github.com/bids-standard/bids-validator/blob/4c1be20980b1215d45aee5e595b62c14bf2604e2/bids-validator/tests/type.spec.js#L373-L390

> How does one include the optional fields like MNI152NLin2009[a-c][Sym|Asym] (a-c and Sym/Asym) in regex?

You could write it all out, like I did in the JSON schema: https://github.com/bids-standard/bids-validator/blob/4c1be20980b1215d45aee5e595b62c14bf2604e2/bids-validator/validators/json/schemas/common_definitions.json#L21-L28

Or you go over to https://regex101.com/ and check what regexp works. But I suggest the former, not the latter.

**Review by sappelhoff — COMMENTED** [review]
please also check the session level rules, etc.

**Comment by sappelhoff** [comment]
@adam2392 I added some commits (including a force push for rebasing, sorry), so please *before* you continue to work, do:

- `git stash` (in case you have any non committed changes)
- `git pull` and then
- `git reset --hard origin/space`
- `git stash apply` (in case you had previous non committed changes that you now want to bring back)

In particular I:
- added a CI job to test against bids-examples, because there are several datasets that make use of `space` ... fixes #1164 
- fixed your regexp
- made a style linebreak the circleci CI script

**Comment by sappelhoff** [comment]
@adam2392 is something holding you back from finishing this PR? Or is it more of a "finding time to do it" issue (which is absolutely fine)?

**Comment by adam2392** [comment]
Yeah sorry didn't have time, but procrastinated a bit this morning and hopefully this is closer to being done / done. LMk. 

FYI: currently the validator allows other entities into the `*_electrodes.tsv` and `*coordsystem.json` files even though they are not technically allowed in the spec.

**Comment by sappelhoff** [comment]
> FYI: currently the validator allows other entities into the *_electrodes.tsv and *coordsystem.json files even though they are not technically allowed in the spec.

yes, thanks for the note, see also: https://github.com/bids-standard/bids-examples/issues/244

**Review by sappelhoff — APPROVED** [review]
I added the regexps and tests for EEG.

> hopefully this is closer to being done / done

I think it's done

**Pull request merged**
