### PR TITLE
FIX: Strip UTF-8 BOM from TSV contents

### LINKED ISSUE #878: UTF-8 BOM characters not supported
When a file is formatted in UTF-8 with BOM (which is a standard utf-8 file format), this BIDS validator will issue errors when reading the byte order marker (ï»¿). For example, this is the output:

Location:
BIDS/sub-01/eeg/sub-01_task-DKVisualOddballactiCHampslim4142_channels.tsv

Reason:
Tabular file contains custom columns not described in a data dictionary

Evidence:
Columns: ï»¿name not defined, please define in: /task-DKVisualOddballactiCHampslim4142_channels.json, /channels.json,/sub-01/sub-01_task-DKVisualOddballactiCHampslim4142_channels.json,/sub-01/sub-01_channels.json,/sub-01/eeg/sub-01_task-DKVisualOddballactiCHampslim4142_channels.json,/sub-01/eeg/sub-01_channels.json

### PR DESCRIPTION
**Pull request by effigies**
Fixes #878.

### CODE REVIEW

**Review by rwblair — APPROVED** [review]
Straight forward and simple, lgtm.

**Comment by 62442katieb** [comment]
Agreed! Looks good.

**Comment by effigies** [comment]
Thanks for the review! I think this might be my first JS pull request...

**Comment by dmedine** [comment]
I just now (9:25 am Central European time, 3.12.2019) tried the validator on a data set with the BOMs inside on the web form (http://bids-standard.github.io/bids-validator/) and it is still throwing the same error:

Location:

BIDS/sub-01/eeg/sub-01_task-DKVisualOddballactiCHampslim4142_events.tsv
Reason:

First column of the events file must be named 'onset'
Line: 1

ï»¿onsetdurationsampletrial_typevalue

Does the form not point to the latest version of the code? Or is this still an issue. I am sorry, I don't know much about javascript or else I would make the PR myself.

**Comment by effigies** [comment]
The website has not been updating lately... Can you install locally?

**Comment by dmedine** [comment]
Yes, but I was hoping to get the web app updated as well. I work for Brain Products and we are about to release an opensource tool for converting recordings made by our software to BIDS and we were hoping to point our customers to the web app to validate their data sets since it is so handy. Is there any chance of it getting updated sometime soon?

**Comment by effigies** [comment]
Yes. We've been prioritizing restoring the automatic process, but the one on the web is old and should be updated manually at this point.

**Comment by effigies** [comment]
@dmedine The website has been updated. Can you verify that the issue is resolved for you?

**Comment by dmedine** [comment]
@effigies Sorry for the lag time. I just checked again and I am still getting the identical error related to the BOM character.

**Comment by effigies** [comment]
Could you provide an example file?

**Comment by dmedine** [comment]
Sorry for the constant lag time in my responses. I do very much appreciate your attention to this matter! Here is a data set that should key off the error: https://drive.google.com/open?id=1K4hu7wpV4jmarwCgtgUR_7e5sjTuSqdf

**Pull request merged**
