### PR TITLE
Implementation of .bidsignore

### PR DESCRIPTION
**Pull request by chrisgorgo**
Checks for presence of /.bidsignore and reads the exclusion patters from it.

### CODE REVIEW

**Comment by chrisgorgo** [comment]
@yarikoptic, @satra  - would love to hear what do you think

**Comment by yarikoptic** [comment]
Well, I think it is/will be great - exactly what we need! ;)
I forgot though already (if ever knew) how to "try" anything from the land of node

**Comment by chrisgorgo** [comment]
Try this out: https://github.com/INCF/bids-validator#development

**Comment by yarikoptic** [comment]
I guess nmp install installs it system or user wide... Don't want to overload default one... How to create some kind of sandbox like virtualenv in python?

**Comment by chrisgorgo** [comment]
Unless you pass `-g` `npm install` performs a local install in the current directory.

**Comment by yarikoptic** [comment]
Ah, great to know, thanks. I Will try when get back to the laptop and if would still be able to type

**Comment by yarikoptic** [comment]
FWIW -- seems to work lovely for me (thanks!).  Although with the already implemented `ignore all .files` my usecases are largely addressed without requiring .bidsignore ;)

**Comment by chrisgorgo** [comment]
Awesome! Thanks for testing!

**Pull request merged**
