### PR TITLE
FIX: Normalize TSV end-of-line without stripping all whitespace

### LINKED ISSUE #1113: Validator should ensure TSV files do not contain a tab character before the linebreak
As discussed [here](https://github.com/bids-standard/bids-matlab/issues/96), the bids validator accepts this file from openneuro:
https://openneuro.org/crn/datasets/ds003195/snapshots/1.0.3/files/participants.tsv
that contains a tab at the end of each line. The question is whether this is indeed a compliant file.

### PR DESCRIPTION
**Pull request by effigies**
Fixes #1113.

TODO:

* [x] Test that empty columns (e.g., `\t\t` or `\t$`) raise an error

### CODE REVIEW

**Comment by rwblair** [comment]
@effigies that test look ok or did you want something more sophisticated?

**Comment by effigies** [comment]
I had something else I was working on, but it wasn't raising expected errors. I'll push it in whatever state I get it to by the end of the day so you can see.

**Comment by sappelhoff** [comment]
It seems like I made a mess out of this when trying to merge `master` ... very sorry about that.

Can somebody tell me where I went wrong?

1. I updated my local `master` with upstream
1. I checked out @effigies  branch
1. I ran `git merge master`
1. this resulted in conflicts (`yarn.lock` was deleted upstream, but was present here)
1. I ran `git add .`, making sure that the deleted `yarn.lock` gets "staged"
1. I ran `git commit -m "merge master"`

And then we are at the current stage, where everything seems messed up.

To "make it all good again", I tried `git revert 53c69b0` (my "merge master" commit), but it turns out to be complicated to do with a "merge commit"

**Comment by sappelhoff** [comment]
Could it be that this is a GitHub issue? ... I merged `master` and then lots of "changes" showed up, that are actually not changes but stuff that is already like that in "master". Then I finally managed to revert my "merge master" because I thought something was wrong. ... and now it looks like I delete those files.

It's utterly confusing. It'd probably be cleanest to get these commits onto a clean up to date master:
- 786cfbb
- 1f98cd1d4c7f1cc672cd916ab5ee5e2da2e0d874

**Comment by sappelhoff** [comment]
okay, I did the cherry-picking solution.

see: https://github.com/bids-standard/bids-validator/pull/1240

**Pull request closed without merging**
