### PR TITLE
Phenotypic data

### PR DESCRIPTION
**Pull request by constellates**
Allow .tsv and .json phenotype data.

### CODE REVIEW

**Comment by constellates** [comment]
for issue #201

**Comment by chrisgorgo** [comment]
Could we add the following checks to this feature:
- participant_id column is present in each phenotypic tsv file
- values from participant_id columns match to "sub-*" folders

Basically we should apply the same tests to phenotypic files as we apply to participants.tsv

**Comment by constellates** [comment]
With regards to matching participant_id columns to "sub-*" folders, does every .tsv in the phenotype directory need to have a row for every subject or are there any cases where portions of subjects would be split across multiple .tsv files within the phenotype directory?

**Comment by chrisgorgo** [comment]
I think we should allow subsets here. It is likely that certain subjects
did not get any measurements from a particular tool and then they will not
be included in the corresponding .tsv file.

We should however catch a situation in which a a subject label that does
not occur in the sub-\* folder happens.

**Comment by constellates** [comment]
This has been updated to test phenotype tsvs against the same basic checks as participants.tsv. The one exception is that participants.tsv files must list every subject in the dataset but phenotype files may list only a subset. An error will be thrown if they list any subjects not found in the dataset.

Definitely check the "reason" changes in the list at utils/issues.js to make sure they sound correct. I added one new issue and modified another to let it apply to phenotype and participants files.

**Comment by constellates** [comment]
Also here are two screen shots of the new issue. It looks fine if there's a reasonable amount of subject differences but becomes a mess if there are a ton. Let me know if you'd like any changes to this output.

screen shot 2016-10-17 at 4 31 36 pm

screen shot 2016-10-17 at 4 29 09 pm

**Comment by chrisgorgo** [comment]
Nice! Is this an error you forced or are you getting this on vanilla ds000030 dataset?

**Comment by constellates** [comment]
It's a forced error. I only downloaded the metadata and a subset of the subjects from openfmri.

**Comment by chrisgorgo** [comment]
Great. LGTM. Merge when ready.

**Pull request merged**
