### PR TITLE
Print version number in standard out.

### LINKED ISSUE #770: Print version number in standard out.
Would be useful in situation where bids-validator is being embedded in reports:
https://github.com/poldracklab/fmriprep/pull/1583

### PR DESCRIPTION
**Pull request by david-nishi**
closes #770 
logs `bids-validator@x.x.x` at start

### CODE REVIEW

**Comment by nellh** [comment]
This will break any JSON readers (OpenNeuro). It should only be printed when the --json flag is not present.

**Comment by david-nishi** [comment]
Thanks for the catch!

**Comment by sappelhoff** [comment]
@DaNish808 if this PR fixes #770, ...

then perhaps you could edit your original post to include the words `closes` or `fixes` right in front of the `#770` --> `closes #770` ... then [GitHub will automatically close that issue upon a merge](https://help.github.com/en/articles/closing-issues-using-keywords).

I have noticed that this could also have been done in https://github.com/bids-standard/bids-validator/pull/793 and https://github.com/bids-standard/bids-validator/pull/794

But then again: Perhaps you are already aware of it, and it's intentional that you don't close those issues - in that case, sorry for lecturing :-)

**Comment by david-nishi** [comment]
@sappelhoff useful trick! Thanks for sharing :D

**Pull request merged**
