### PR TITLE
run node tests in github actions

### PR DESCRIPTION
**Pull request by rwblair**
See if it gets same problem as in #1358

### CODE REVIEW

**Comment by rwblair** [comment]
I'm still clueless as to why fs.existsSync returns false in gitlab, circleci, and githubactions but true when in a proper shell. Maybe worth testing for existeance some other way and catching ENOENT code.

**Comment by effigies** [comment]
> will --colors work for windows gitlab?

LOLNO

**Comment by effigies** [comment]
@rwblair Assume you've seen https://stackoverflow.com/questions/66185466/npm-script-fails-is-not-recognized-as-an-internal-or-external-command? It's not obvious that there are useful suggestions there, but it does seem that for some reason we're generating unix test scripts when we should be generating Windows.

**Comment by rwblair** [comment]
@effigies thank you. Made me wonder why things in the package.json were calling bins with relative paths. Turns out to be for no good reason. Now its failing for new reasons.

Also looks like eslint on ubuntu might not really be running. The command takes a minute on my local machine, but is done in seconds on ci.

**Comment by effigies** [comment]
This looks good. Cleaned up in #1426 with one additional commit.

**Pull request closed without merging**
