### PR TITLE
Improve UTF-8 support in browser environments

### PR DESCRIPTION
**Pull request by nellh**
This fixes incorrect alignment of some UTF-8 characters due to the fromCharCode approach not handling multi-byte characters and other details of UTF-8 vs the native UTF-16 byte encoding.

Fixes #946 and #878 

@alexrockhill Can you please test if this resolves the web validator issue for you from #946?

### CODE REVIEW

**Comment by effigies** [comment]
Probably also fixes #917...

**Comment by alexrockhill** [comment]
> This fixes incorrect alignment of some UTF-8 characters due to the fromCharCode approach not handling multi-byte characters and other details of UTF-8 vs the native UTF-16 byte encoding.
> 
> Fixes #946 and #878
> 
> @alexrockhill Can you please test if this resolves the web validator issue for you from #946?

Unfortunately, no, that same error persists. Copying the minimally reproducible example here if that's any help.

```
import os.path as op
import mne

from mne_bids import make_bids_basename, write_raw_bids

subject_id = '01'
subject_id2 = '02'
session_id = '01'
run = '01'
acq = '01'
run2 = '02'
task = 'testing'

bids_basename = make_bids_basename(
    subject=subject_id, session=session_id, run=run, acquisition=acq,
    task=task)

bids_root = './bids_dataset'
data_path = op.join(mne.datasets.testing.data_path(), 'EDF')
raw_fname = op.join(data_path, 'test_reduced.edf')

raw = mne.io.read_raw_edf(raw_fname)

write_raw_bids(raw, bids_basename, bids_root, overwrite=True)
```

**Comment by alexrockhill** [comment]
Screen Shot 2020-04-27 at 9 38 39 AM

Maybe this is the issue...
https://kevin.burke.dev/kevin/node-js-string-encoding/

Is there any chance it's actually UTF-16 when it's read in by Node and it's being decoded as UTF-8?

**Comment by nellh** [comment]
> Screen Shot 2020-04-27 at 9 38 39 AM
> 
> Maybe this is the issue...
> https://kevin.burke.dev/kevin/node-js-string-encoding/
> 
> Is there any chance it's actually UTF-16 when it's read in by Node and it's being decoded as UTF-8?

For the web validator, Node is only used during the build process and validation runs in your browser. I've confirmed that the build step is correctly preserving the UTF-8 source when outputting the web bundle.

I did test with your MNE example and this PR does fix the issue for me - so a couple questions:

* What browser and OS version are you testing with?
* How are you running the web validator to test? You should check out this branch and run `yarn web-dev` or `npm run web-dev`.

**Comment by alexrockhill** [comment]
> > Screen Shot 2020-04-27 at 9 38 39 AM
> > Maybe this is the issue...
> > https://kevin.burke.dev/kevin/node-js-string-encoding/
> > Is there any chance it's actually UTF-16 when it's read in by Node and it's being decoded as UTF-8?
> 
> For the web validator, Node is only used during the build process and validation runs in your browser. I've confirmed that the build step is correctly preserving the UTF-8 source when outputting the web bundle.
> 
> I did test with your MNE example and this PR does fix the issue for me - so a couple questions:
> 
> * What browser and OS version are you testing with?
> * How are you running the web validator to test? You should check out this branch and run `yarn web-dev` or `npm run web-dev`.

I was using `yarn web-dev` with Chrome and OSX Catalina 10.15.3.

Hmmm maybe I wasn't running it appropriately.

Update: also tried with `npm run web-dev` and it didn't work either. I tried FireFox as well and it didn't work either, same error. Not sure how to resolve this discrepancy, do you know the best way to test?

**Comment by rwblair** [comment]
@alexrockhill Can you try and validate your dataset on openneuro.org directly? This change to the validator has been deployed there.

**Comment by alexrockhill** [comment]
It passed on OpenNeuro, thanks @nellh for the help/PR and thanks @rwblair for the review and following up!

**Pull request merged**
