### PR TITLE
Close nifti files #675

### PR DESCRIPTION
**Pull request by david-nishi**
* [x] close all nifti files streams after getting header

### CODE REVIEW

**Comment by nellh** [comment]
I've been testing this with a hard limit of 64 or 128 files and I am not seeing a difference between this PR and master for reproducing the issue from #675. Does the structure of the dataset matter for testing this? I'm using a dataset with 147 nifti files.

**Comment by david-nishi** [comment]
@nell i believe it only runs fs.open on annexed files, if that's related

**Comment by nellh** [comment]
I think this isn't needed with the concurrency limiting introduced in #687

**Comment by yarikoptic** [comment]
FWIW, I have ran

```
while true; do nl=$(ls -l /proc/59167/fd 2>/dev/null | wc -l ); if [ $nl -gt 100 ]; then echo "Got $nl files. I will list a sleep a little to rest"; ls -l /proc/59167/fd; sleep 10; fi; done 2>&1 | tee /tmp/toomany-open
```

and eventually I got "Got 4097 files. I will list a sleep a little to rest" and indeed it was lots of annex'ed .nii.gz files:

```
[bids@rolando tmp] > tail toomany-open
...
lr-x------ 1 bids bids 64 Jan 12 15:53 999 -> /usr/local/singularity_v2.5.1/var/singularity/.../.git/annex/objects/08/XJ/MD5E-s533081--e5095d4b869a241e06664d81bb8288e7.nii.gz/MD5E-s533081--e5095d4b869a241e06664d81bb8288e7.nii.gz
```

so may be this PR should be re-opened/re-considered?

**Pull request closed without merging**
