### PR TITLE
Issue #265

### PR DESCRIPTION
**Pull request by ntraut**

### CODE REVIEW

**Comment by chrisgorgo** [comment]
@suyashdb could you test this?

**Comment by constellates** [comment]
This PR didn't trigger the CI tests for some reason. I thought it could be related to originating from a fork, but there's plenty of fork based PRs in the history that triggered tests. I'm looking into it.

**Comment by suyashdb** [comment]
@chrisfilo - its is still generating error 


```
login1.ls5(26)$ bids-validator/bin/bids-validator /corral-repl/utexas/poldracklab/openfmri/inprocess/dsmarcel_plank_institute/copy_inprocess_MP/
/home1/04275/suyashdb/node_modules/async/dist/async.js:825
        return i < len ? { value: obj[key], key: key } : null;
                         ^

RangeError: Maximum call stack size exceeded
    at next (/home1/04275/suyashdb/node_modules/async/dist/async.js:825:26)
    at replenish (/home1/04275/suyashdb/node_modules/async/dist/async.js:872:28)
    at iterateeCallback (/home1/04275/suyashdb/node_modules/async/dist/async.js:866:17)
    at /home1/04275/suyashdb/node_modules/async/dist/async.js:843:16
    at NIFTI.async.forEachOf.issues.push.Issue.file (/home1/04275/suyashdb/bids-validator/validators/nii.js:217:21)
    at replenish (/home1/04275/suyashdb/node_modules/async/dist/async.js:881:17)
    at iterateeCallback (/home1/04275/suyashdb/node_modules/async/dist/async.js:866:17)
    at /home1/04275/suyashdb/node_modules/async/dist/async.js:843:16
    at NIFTI.async.forEachOf.issues.push.Issue.file (/home1/04275/suyashdb/bids-validator/validators/nii.js:217:21)
    at replenish (/home1/04275/suyashdb/node_modules/async/dist/async.js:881:17)

```

**Comment by chrisgorgo** [comment]
@suyashdb Your stacktrace indicates the use of `async.forEachOf` at `bids-validator/validators/nii.js:217`. This PR switches to `eachOfLimit`. Are you sure you are testing the code from this PR?

**Comment by suyashdb** [comment]
@chrisfilo - Yes above error was generated as i used wrong version of validator. 

i was able to run validator on same dataset without any errors with this new PR.

**Pull request merged**
