### PR TITLE
Add tests against tsv headers to check for duplicate, empty, and 'n/a' values.

### LINKED ISSUE #1465: TSV validation: Error when column header is blank, duplicated, or `"n/a"`
related to https://github.com/bids-standard/bids-specification/issues/1105

~~We still need to add a note to the spec about this as well.~~ done in bids-standard/bids-specification#1116

### PR DESCRIPTION
**Pull request by rwblair**
Fixes #1465

### CODE REVIEW

**Review by sappelhoff — APPROVED** [review]
LGTM, ready to merge @rwblair?

**Comment by sappelhoff** [comment]
oh oh 😬 the "files changed" tab looks broken

**Comment by rwblair** [comment]
silly workaround to get PR to see commits pushed to master since PR opened:
https://stackoverflow.com/questions/16306012/github-pull-request-showing-commits-that-are-already-in-target-branch

**Comment by sappelhoff** [comment]
Ahhh nice, that'll come in handy. I've seen this issue several times now

**Pull request merged**
