### PR TITLE
Bump version number to 1.5.5-dev.0

### LINKED ISSUE #1080: After a release, bump the version number of the development version
Hello, I'm running into an issue with `bids-validator`; specifically, we're running a CI job that once installs the latest stable release from NPM, and in another set of runs installs the code from the `master` branch. Unfortunately, both versions carry the exact same version number (1.5.4), so there is no way for our tests to find out whether they're being run in an environment with a stable or a development version of the validator. Would it be possible to bump the version number after a release? One could use NPM pre-release version identifiers, such `as 1.5.5-alpha.0`. Any thoughts?

### PR DESCRIPTION
**Pull request by hoechenberger**
Closes GH-1080.

### CODE REVIEW

**Review by adam2392 — APPROVED** [review]

**Review by agramfort — APPROVED** [review]

**Comment by effigies** [comment]
Lgtm.

**Comment by hoechenberger** [comment]
I'm just going to go ahead and merge this, then

**Comment by sappelhoff** [comment]
this is related to https://github.com/bids-standard/bids-validator/issues/803

... is bumping the version as done in this PR the solution for that issue @rwblair ?

**Comment by sappelhoff** [comment]
also, in https://github.com/bids-standard/bids-validator/commit/7e4daf8eda0c7573e9f2152f1c9050b719c61315 it seems like `lerna.json` is usually updated as well. see also: https://github.com/bids-standard/bids-validator#publishing

**Comment by effigies** [comment]
I'm not sure that updating `lerna.json` makes a difference, since we're not publishing when bumping to a dev version. I guess if @rwblair wants to check when we get to the next release whether changing or leaving it makes more sense?

**Comment by hoechenberger** [comment]
I can of course bump it too in another PR…

**Comment by rwblair** [comment]
I'm going to publish a new release soon, so well see how lerna deals with the dev versioning. I'll be sure to have a dev tag in the master version going forward.

**Comment by sappelhoff** [comment]
awesome, thanks. I''ll close #803

**Pull request merged**
