### PR TITLE
Show web version as CircleCI artefact

### PR DESCRIPTION
**Pull request by chrisgorgo**

### CODE REVIEW

**Comment by chrisgorgo** [comment]
This is ready for review. You can now test the web version of the validator for each commit directly from CircleCI https://865-37161308-gh.circle-artifacts.com/0/home/ubuntu/web_version/index.html

**Comment by suyashdb** [comment]
https://865-37161308-gh.circle-artifacts.com/0/home/ubuntu/web_version/index.html seems to be commit specific web version link. Can you share how did you get this..? How i can get web version links for my commits? I tried merging this branch with mine to get to web version link but no success. 
Neither on https://circleci.com/gh/INCF/bids-validator/865?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link  i am able to find this link.

code added to circle.yml looks fine and working properly(looking at the build) to me..

**Comment by chrisgorgo** [comment]
It's on circle CI in the artifacts tab. You need to be logged in to see it.
image

**Comment by suyashdb** [comment]
Perfect! I tested it on ds121 version, and web version works perfect..

**Pull request merged**
