### PR TITLE
Symlink Validity Checks (please test)

### PR DESCRIPTION
**Pull request by constellates**
I've re-applied the symlink test on top of the current master. Please test and let me know if you're still experiencing issues.

I haven't been able to reproduce the issue with this error being thrown on validly symlinked datasets. To test I've been using the symlink based downloads from the bids-core and intentionally orphaning one of them. I've tested in the browser and node. So if you see this issue again let me what I should try to reproduce it.

### CODE REVIEW

**Comment by chrisgorgo** [comment]
I'm still running into the same issue. Namely:

```
[filo@chrisbook bids-validator]$ bin/bids-validator /data/bids_examples/symlinked/ds006/
    1: This file is too small to contain the minimal NIfTI header. (code: 36)
        /sub-01/ses-retest/anat/sub-01_ses-retest_T1w.nii.gz
        /sub-01/ses-retest/anat/sub-01_ses-retest_inplaneT2.nii.gz
        /sub-01/ses-retest/func/sub-01_ses-retest_task-livingnonlivingdecisionwithplainormirrorreversedtext_run-01_bold.nii.gz
        /sub-01/ses-retest/func/sub-01_ses-retest_task-livingnonlivingdecisionwithplainormirrorreversedtext_run-02_bold.nii.gz
        /sub-01/ses-retest/func/sub-01_ses-retest_task-livingnonlivingdecisionwithplainormirrorreversedtext_run-03_bold.nii.gz
        /sub-01/ses-retest/func/sub-01_ses-retest_task-livingnonlivingdecisionwithplainormirrorreversedtext_run-04_bold.nii.gz
        /sub-01/ses-retest/func/sub-01_ses-retest_task-livingnonlivingdecisionwithplainormirrorreversedtext_run-05_bold.nii.gz
        /sub-01/ses-retest/func/sub-01_ses-retest_task-livingnonlivingdecisionwithplainormirrorreversedtext_run-06_bold.nii.gz
        /sub-01/ses-test/anat/sub-01_ses-test_T1w.nii.gz
        /sub-01/ses-test/anat/sub-01_ses-test_inplaneT2.nii.gz
        /sub-01/ses-test/func/sub-01_ses-test_task-livingnonlivingdecisionwithplainormirrorreversedtext_run-01_bold.nii.gz
        ... and 207 more files having this issue (Use --verbose to see them all).

    1: Not all subjects contain the same files. Each subject should contain the same number of files with the same naming unless some files are known to be missing. (code: 38)
        /sub-02/ses-retest/func/sub-02_ses-retest_task-livingnonlivingdecisionwithplainormirrorreversedtext_run-03_bold.nii.gz
        /sub-02/ses-retest/func/sub-02_ses-retest_task-livingnonlivingdecisionwithplainormirrorreversedtext_run-04_bold.nii.gz
        /sub-03/ses-test/func/sub-03_ses-test_task-livingnonlivingdecisionwithplainormirrorreversedtext_run-05_bold.nii.gz
        /sub-03/ses-test/func/sub-03_ses-test_task-livingnonlivingdecisionwithplainormirrorreversedtext_run-05_events.tsv
        /sub-05/ses-test/func/sub-05_ses-test_task-livingnonlivingdecisionwithplainormirrorreversedtext_run-02_bold.nii.gz
        /sub-05/ses-test/func/sub-05_ses-test_task-livingnonlivingdecisionwithplainormirrorreversedtext_run-02_events.tsv
        /sub-06/ses-test/func/sub-06_ses-test_task-livingnonlivingdecisionwithplainormirrorreversedtext_run-02_bold.nii.gz
        /sub-06/ses-test/func/sub-06_ses-test_task-livingnonlivingdecisionwithplainormirrorreversedtext_run-02_events.tsv
        /sub-07/ses-test/func/sub-07_ses-test_task-livingnonlivingdecisionwithplainormirrorreversedtext_run-04_bold.nii.gz
        /sub-07/ses-test/func/sub-07_ses-test_task-livingnonlivingdecisionwithplainormirrorreversedtext_run-04_events.tsv

        Summary:                   Available Tasks:                                                    Available Modalities: 
        387 Files, 187.82kB        living-nonliving decision with plain or mirror-reversed text        T1w                   
        14 - Subjects                                                                                  inplaneT2             
        2 - Sessions     
```

Even though:

```
[filo@chrisbook bids-validator]$ ls -al /data/bids_examples/symlinked/ds006/sub-01/ses-retest/anat/sub-01_ses-retest_T1w.nii.gz
lrwxrwxrwx 1 filo filo 54 Apr 27 20:26 /data/bids_examples/symlinked/ds006/sub-01/ses-retest/anat/sub-01_ses-retest_T1w.nii.gz -> /data/openfmri/ds006B/sub001/anatomy/highres001.nii.gz
[filo@chrisbook bids-validator]$ nib-ls /data/bids_examples/symlinked/ds006/sub-01/ses-retest/anat/sub-01_ses-retest_T1w.nii.gz
/data/bids_examples/symlinked/ds006/sub-01/ses-retest/anat/sub-01_ses-retest_T1w.nii.gz float32 [160, 192, 192] 1.00x1.33x1.33
```

Let me know if there is any other info I can provide to help debug this.

**Comment by constellates** [comment]
Thanks, I'm still struggling to recreate this. Can you send me that single file and the single file symlink and I'll try again?

**Comment by constellates** [comment]
This should be fixed now. I was using `fs.lstat` incorrectly and that file was getting flagged as too small to contain a header because it was looking at the size of the symlink and not the file. My datasets weren't doing that because the symlink paths were longer and created a link file bigger than a scan header.

I also verified our other uses of `fs.stat`, `fs.lstat` and fixed summary data collection so we're showing the full dataset size and not the size of the collected symlinks.

Let me know if you're still seeing issues.

**Comment by chrisgorgo** [comment]
Works!

**Pull request merged**
