### PR TITLE
NGFF support

### PR DESCRIPTION
**Pull request by TheChymera**
Draft for now.

### CODE REVIEW

**Comment by TheChymera** [comment]
@effigies could you help with a review? and thanks :3

**Review by effigies — APPROVED** [review]
Looks good. Pinging @sappelhoff and linking https://github.com/bids-standard/bids-examples/pull/315.

**Comment by TheChymera** [comment]
Tests passed against the updated example branch (linked by @effigies above) in [058c83a](https://github.com/bids-standard/bids-validator/pull/1467/commits/058c83a18d1d63235f726b4b7f1c19b5c1e4c022). Reverting to bids-standard/bids-examples master in [d7d3837](https://github.com/bids-standard/bids-validator/pull/1467/commits/d7d3837fdf803b14ed9b52f73ddd369dbbd01508).

**Review by sappelhoff — APPROVED** [review]
lgtm, thanks!

**Pull request merged**
