### PR TITLE
FIX: Add echo entity to MPM/MTS

### PR DESCRIPTION
**Pull request by effigies**
By my reading of [anat.yaml](https://github.com/bids-standard/bids-specification/blob/7cdeadf6d0f448cbf5fe0d30d75787fb3166bbee/src/schema/datatypes/anat.yaml#L140-L157), this needs fixing. Also leading to an error in https://github.com/effigies/BIDS-examples/tree/qmri/qmri_mpm.

### CODE REVIEW

**Review by tsalo — APPROVED** [review]
LGTM! Not sure why the test is failing though.

**Comment by effigies** [comment]
Yeah, I restarted it and it still fails. @rwblair any ideas? It's possible that some dependency just made a release and broke everything. Will know that when you update #1183.

**Comment by effigies** [comment]
Just searching, we might need to look into something like https://github.com/facebook/jest/issues/8384#issuecomment-674351539 or https://github.com/facebook/jest/issues/9881#issuecomment-654627853.

**Comment by nellh** [comment]
Yeah, this looks like it's just inconsistent performance on Circle. A higher timeout can be passed as the third argument to the it() call - the two node spawn tests that reference the valid_headers dir should just have the timeout raised. It's probably slow just because it ends up accessing more of node_modules in the new node process than the other tests.

**Pull request merged**
