### PR TITLE
Add directory existence check

### PR DESCRIPTION
**Pull request by SetCodesToFire**
This PR is for the issue #383

### CODE REVIEW

**Comment by chrisgorgo** [comment]
Great! Could you add some tests?

**Comment by SetCodesToFire** [comment]
correct
Resolved 😄

**Comment by SetCodesToFire** [comment]
Hi @chrisfilo 
I will be happy to add tests for this.

**Comment by SetCodesToFire** [comment]
@chrisfilo Added the test. 😄

**Comment by SetCodesToFire** [comment]
@chrisfilo There is some error in the tests. I re-confirmed if this is due to the inclusion of my test code and came to the conclusion that the error is in the previous written code. 

Steps performed:
1) Cloned bids-validator to my drive
2) cd into it and ran npm install
3) ran npm test

Still i got the same errors that i got from running npm test in the forked repo.

Help me .

**Comment by chrisgorgo** [comment]
The test I see failing is the one that you just added: https://circleci.com/gh/INCF/bids-validator/938?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by SetCodesToFire** [comment]
Hi @chrisfilo ,
I never did much tests in the past. Can you please tell me why the code is wrong. Do I need to create a file in the tests/data folder where I should create random xyz paths. I failed many a time consecutively now.

**Comment by SetCodesToFire** [comment]
Hi @chrisfilo ,
I am so happy 😄 finally the checks have passed.

**Comment by chrisgorgo** [comment]
Great! Thanks for your contribution!

PS A tip for the future - please refrain from editing or deleting posts/comments. It makes communication confusing.

**Comment by SetCodesToFire** [comment]
Sure, Thank you, 😄

**Pull request merged**
