### PR TITLE
Re-implement testing "units" in BIDS metadata

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**
Addresses bids-standard/bids-validator#71.

This code has been sitting unused for a long time. Does it need some overhauling or more testing?

### CODE REVIEW

**Review by sappelhoff — CHANGES_REQUESTED** [review]
I think this needs a lot of overhaul :-)

https://github.com/bids-standard/bids-validator/issues/969#issuecomment-932894245

**Comment by DimitriPapadopoulos** [comment]
Yes, for example:
> Evidence: Subunit (uV) of unit uV is invalid. 

In example [`ieeg_epilepsy/sub-01/ses-postimp/ieeg/sub-01_ses-postimp_task-seizure_run-01_channels.tsv`](https://github.com/bids-standard/bids-examples/blob/master/ieeg_epilepsy/sub-01/ses-postimp/ieeg/sub-01_ses-postimp_task-seizure_run-01_channels.tsv) units are **`uV`** (which is the recommended [CMIXF-12](https://people.csail.mit.edu/jaffer/MIXF/CMIXF-12) form).

**Comment by DimitriPapadopoulos** [comment]
One problem was the `µ` instead of `u` for [micro](https://www.wikiwand.com/en/Micro-) (actually both `µ` and `u` are valid for backwards compatibility):
https://github.com/bids-standard/bids-validator/blob/abb700c79b6d79683598a394aea5e0573b33412b/bids-validator/utils/unit.js#L92

Another one was the `Ω` instead of `Ohm` (again both `Ω` and `Ohm` are valid for backwards compatibility):
https://github.com/bids-standard/bids-validator/blob/abb700c79b6d79683598a394aea5e0573b33412b/bids-validator/utils/unit.js#L37

**Comment by DimitriPapadopoulos** [comment]
See instructions here:
https://github.com/bids-standard/bids-validator/blob/abb700c79b6d79683598a394aea5e0573b33412b/bids-validator/utils/unit.js#L140-L144

**Comment by DimitriPapadopoulos** [comment]
I suspect the **ci/circleci: test** failure is unrelated to this pull request. In any case the error messages don't make any sense.

See bids-standard/legacy-validator#1358.

**Pull request closed without merging**
