### PR TITLE
HED integration part 2 (semantic validation)

### PR DESCRIPTION
**Pull request by happy5214**
This branch updates the HED validation in BIDS to version 1.0 of the `hed-validator` JS package, which implements semantic validation. As part of this, the event validation has been migrated to `Promise`s to allow for the `Promise` returned by `hed-validator`. Tests have been included.

### CODE REVIEW

**Comment by happy5214** [comment]
Has anyone had a chance to look at this? Are the failed tests holding this up?

**Comment by VisLab** [comment]
I was wondering what the status of this pull request was.  We did an earlier pull request which has already been incorporated into the BIDS validator. The earlier revision included syntactic validation for HED (Hierarchical Event Descriptor Tags).  This included things like making sure parentheses matched in HED tag strings. The current pull request includes semantic validation against the HED hierarchy.  Some restructuring was needed in the events subdirectory. These changes bring the structure of the code more in line with some of the later code in the rest of the validator. I believe some additional error codes were used.   

Note: A group of us is working to consolidate all of the tools associated with HED on a github website which can be referenced through hedtags.org.  We are working on additional code support and testing for the online python validator and are trying to keep the javascript validator in sync as much as possible. A permanent home for the online python HED validator is planned for the UCSD Supercomputer Center after testing and consolidation are completed.

**Comment by effigies** [comment]
I guess the status is we're waiting for someone familiar with Javascript to review this. There are also errors in the tests that are probably worth resolving, and it would be good to merge or rebase the `master` branch to ensure that we're not conflicting with recent changes.

We don't really have a standard review process, but if I can improvise one right here, I'd say we need to check the following:

* [ ] Relation to BIDS specification
  * [ ] This PR brings the validator into better conformance with the standard
  * [ ] This PR accompanies a change in the standard
* [ ] Manual testing; a reviewer should be able to, by reading the standard, modify a valid dataset to be invalid
* [ ] Code review; a competent review of the javascript
  * [ ] Does what PR claims
  * [ ] Edge cases are covered
  * [ ] No glaring security issues
  * [ ] Fits neatly into overall architecture (I'll include style here)
  * [ ] [Coverage](https://codecov.io/gh/bids-standard/bids-validator/pull/840/diff) - should not decrease, ideally all new lines are covered, including error conditions (since that's what the validator is designed to look for)
    * This looks pretty good to me. There are a couple missed lines, and a reviewer can decide whether they're significant enough to warrant an additional test.

If we don't have anybody who's competent to review all of these pieces together, we can try to split up tasks.

For manual testing, do you have an example dataset you would recommend? And specific rules in the standard that should now be enforced that weren't previously?

For code review, do you have any reviewers you would suggest? @rwblair @nellh Feel free to nominate people as well. And we'll probably want some previous contributor for the fit/coverage review.

**Comment by happy5214** [comment]
I have rebased the branch onto `master`.

The CircleCI issues appear to be caused by failures to load npm packages. I'll note that the `hed-validator` package uses `libxmljs`, which does require a C library. This package was chosen for compatibility with the Python version of the HED validator, which uses a similar binding to `libxml`.

**Comment by rwblair** [comment]
@happy5214 Unfortunately I can't find a way to get the webpack build of the validator to work with libxmljs, so this breaks the web validator build.

I'm looking at pure JS replacements that don't rely on libxml so that we could have HED validation on the web based validator.

**Comment by happy5214** [comment]
@rwblair Would [xml2js](https://www.npmjs.com/package/xml2js) be suitable? It's already pulled by bids-validator through other existing dependencies, so it should work.

**Comment by rwblair** [comment]
@happy5214 Playing with a fork of the hed-validator now, unfortunately xml2js is not a straightforward replacement. I'm going to play with it a bit more to see if I can get a working version, if so I'll open a pr against hed-javascript repo. It seems to be the most popular alternative to libxmljs.

**Comment by happy5214** [comment]
@rwblair Have you made any progress on it?

**Comment by rwblair** [comment]
Apologies for the delay still working on it. I'm trying to get a library that can access parent nodes in a parsed xml document working so that we won't have to reimplement that, something that xml2js and xml2js-xpath don't seem capable of.

**Comment by happy5214** [comment]
Here's my attempt to do it with xml2js. First, set the Parser option `explicitChildren` to `true`. Then, after parsing, run the following recursive function (passing only the root):

```javascript
function setParent(node, parent) {
  node.$parent = parent
  if (node.$$) {
    for (const child of node.$$) {
      setParent(child, node)
    }
  }
}
```

`$parent` should then have the parent node.

**Comment by happy5214** [comment]
@rwblair Can you please push your working copy to a fork? I can't really help much without seeing what you've already done.

**Comment by VisLab** [comment]
We seem to be at an impasse here and need to have some additional help/action.   We opened a pull request for HED semantic validation in September.  After a very long time, it was determined that the python library that we were using to convert xml was causing problems for other parts of the validator. We converted our code to xmljs which was already being used by other parts of the validator.  It still seems to be giving someone issues, but until they post their branch and let us help, this PR continues to be delayed.  How can we facilitate this so that we can move forward?

**Comment by rwblair** [comment]
@happy5214 @VisLab I'm sorry for how long this is taking. The canges in this PR do not currently use libxml but I think the hed validator it needs as a dependency still does. I was hesitant to make ya'll rewrite the  hed-standard/hed-javascript package to use xml2js instead of libxmljs. I've spent time here and there going through the hed validator code base trying to understand how best replace libxmljs. My attention has obviously been divided so again I apologize. @happy5214 you probably know the hed validator code base better than anyone, if you have time to attempt to convert it to use xml2js I would be grateful, otherwise I am still committed to attempting to get this to work.

**Comment by happy5214** [comment]
@rwblair What's going on with `fs` not being resolved in the githubPagesTest test?

**Comment by happy5214** [comment]
> @rwblair What's going on with `fs` not being resolved in the githubPagesTest test?

I've fixed the issue by replacing our request library and setting a flag in our package.json. The test now passes.

**Comment by rwblair** [comment]
Thank you so much @happy5214! The changes to the hed validator look good and I was able to get them to work on a build of the static site. I tried to fix the conflicts with master, and am now looking into the async jest tests timing out. Once these work again I'll merge.

**Pull request merged**
