### PR TITLE
Add github actions CI workflow for JS tests, for all OSses

### LINKED ISSUE #1223: Migrate gitlab CI + CircleCI to GitHub Actions?
~I broke gitlab ci with #1221 (just noticed after merging, because the gitlab ci job is apparently not run on PRs?), then tried to fix it with several commits to master, but failed. No idea what the issue is.~

edit to original post: GitLab CI was fixed in https://github.com/bids-standard/bids-validator/commit/5ee85764957b8b07681ac33c92b7d3052c01ce45

But in a separate meeting we agreed that it would be great to consolidate all CIs under GitHub actions. ~That's work in progress now on #1224~

**Update: #1224 was merged into https://github.com/bids-standard/bids-validator/tree/ci/migrate/gh-actions so that in the future someone may pick up that work and complete it. But it'd also be fair enough just to delete https://github.com/bids-standard/bids-validator/tree/ci/migrate/gh-actions and start from scratch, because neither @rwblair nor I have managed to finish that work in more than 6 months.**

### PR DESCRIPTION
**Pull request by sappelhoff**
closes #1223

### CODE REVIEW

**Comment by nellh** [comment]
Is there a good way to run GitHub Actions outside of CI? That's one of the main advantages of GitLab CI (local flexible runners and open source).

**Comment by effigies** [comment]
> Is there a good way to run GitHub Actions outside of CI? That's one of the main advantages of GitLab CI (local flexible runners and open source).

Not really. I found a tool to try to do it, but it was not an exact reproduction, making debugging very unreliable.

**Comment by sappelhoff** [comment]
Mmh, okay - I  wasn't aware of that. Perhaps I should rather try to fix the gitlab CI then. thoughts?

**Comment by nellh** [comment]
It sounds like if we can get the existing test working on GitHub Actions that's going to be the easiest way to get tests running on forks. Can we consolidate the Circle CI scripts on GitHub Actions as well?

**Comment by rwblair** [comment]
Great work @sappelhoff 

From my quick look at the remaining tests that need to be ported over we should be able to get everything into github actions. SSH access will be missed but that platform matrix is very nice.

**Comment by sappelhoff** [comment]
Yes I think migrating the other circleci steps won't be a problem at all. I am just stuck with the scripts in `package.json` and how to refer to them (relative path to executable, or name of executable), but I'll wait for @rwblair to make a PR for that.

**Comment by sappelhoff** [comment]
@rwblair I merged master into this branch, and will now merge this branch into a new branch that is on bids-standard/bids-validator (I just created it for this: https://github.com/bids-standard/bids-validator/tree/ci/migrate/gh-actions), feel free to take it over and make a new PR from that branch once it's ready :-)

I have decided that I'll spend my time on other things first, because our current CI works about right.

We can always delete the branch in the future if noone of us wants to pick up that work, or everyone rather wants to start from scratch

**Pull request merged**
