### PR TITLE
MNT: Bump hed-validator from 3.5.0 to 3.7.1

### LINKED ISSUE #1457: Bump hed-validator version in package-lock.json
[hed-validator](https://github.com/hed-standard/hed-javascript) was updated to v3.7.0 today. This version contains several bug fixes that directly impact validation of BIDS datasets containing HED data, including properly reporting internal errors as `HED_INTERNAL_ERROR` issues instead of failed schema loads and only reporting sidecar issues when they actually occur in the sidecar, instead of also reporting them whenever they are referenced in the TSV file (which can be thousands of times, causing massive slowdowns; see https://github.com/hed-standard/hed-javascript/issues/58 for an example). The bids-validator `package-lock.json` should be updated as soon as is reasonable to pull this update.

### PR DESCRIPTION
**Pull request by rwblair**
fixes #1457

### CODE REVIEW

**Comment by rwblair** [comment]
Looks like new hed-validator uses class properties which aren't supported by our old nextjs/webpack/babel setup. babel es2022 presets include the plugin to handle these.

**Comment by VisLab** [comment]
@rwblair  Do we need to do anything about this or can you do this?  We would like to get this pushed through as it significantly improves the error reporting on the HED side.

**Comment by effigies** [comment]
@VisLab Ross is out for a couple weeks. If your group knows how to fix this and can get tests passing, then I'm happy to merge.

**Comment by happy5214** [comment]
I went ahead and bypassed the issue by releasing version 3.7.1 of `hed-validator`, which refactors the static constants as ordinary module-level constant variables. This should resolve the errors.

**Comment by happy5214** [comment]
@effigies I don't have commit rights to this repository, so I need the `package.json` and `package-lock.json` updated to use version 3.7.1 of `hed-validator`.

```npm install -w bids-validator hed-validator@^3.7.1```

**Comment by effigies** [comment]
githubPagesTest passes. Note that we do see an error:

```
error - Your project has an older version of ESLint installed (5.16.0). Please upgrade to ESLint version 7 or later
```

I will open a separate PR to avoid infecting this one.

**Comment by effigies** [comment]
@happy5214 @VisLab Do you need a validator release, or are you able to work with it as a development version?

**Comment by VisLab** [comment]
Thanks for getting this merged.  We would really like a validator release.
Some of the changes involve eliminating the multiple reporting of the same
issue, which really bogs down the validation process.

**Comment by effigies** [comment]
Looks like I don't have permissions to upload to npm. I'll see if I can get them, but with people on vacation it might be slow...

**Comment by VisLab** [comment]
Understood....your help is much appreciated.

**Comment by effigies** [comment]
Well, managed to tag and push to git with lerna, but attempting to publish to npm is failing.

```
lerna info publish Publishing packages to npm...
lerna info Verifying npm credentials
lerna http fetch GET 200 https://registry.npmjs.org/-/npm/v1/user 431ms
lerna http fetch GET 200 https://registry.npmjs.org/-/org/cjmarkie/package?format=cli 324ms (cache updated)
lerna info Checking two-factor auth mode
lerna http fetch GET 200 https://registry.npmjs.org/-/npm/v1/user 263ms
lerna ERR! Error: Source and destination must not be the same.
lerna ERR!     at /home/chris/.npm/_npx/d5cad42883f80c04/node_modules/fs-extra/lib/util/stat.js:39:17
lerna ERR! lerna Source and destination must not be the same.
```

Might be https://github.com/jprichardson/node-fs-extra/issues/657 but don't have time to track down right now. Tried on two separate computers with different node installations. In case someone else has ideas...

**Comment by rwblair** [comment]
Not sure what was up with lerna. was able to publish just using npm by itself:
https://www.npmjs.com/package/bids-validator

@VisLab  Let us know if the published package works as expected for you.

**Comment by effigies** [comment]
Thanks @rwblair! Please stop working and have a beer.

**Comment by VisLab** [comment]
@effigies @rwblair
Thank you very much for your help!   We'll test it out.

**Comment by rwblair** [comment]
I should be able to take a look at this in a couple hours. Will let you
know what I see.

**Pull request merged**
