### PR TITLE
Update pet.json to accept "n/a" for InjectedMass and SpecificRadioact…

### PR DESCRIPTION
**Pull request by mnoergaard**
This PR solves the issues raised in https://github.com/bids-standard/bids-validator/issues/1326#issuecomment-993344409

This PR updates InjectedMass and SpecificRadioactivity to accept "n/a" according to the PET-BIDS specification. Currently, it only accepts numbers, and therefore complains when a string is entered. Therefore, it has been modified to also accept a string for the case "n/a".

### CODE REVIEW

**Review by sappelhoff — COMMENTED** [review]
thanks @mnoergaard! I pushed a commit that will ensure that the only valid string that can be passed is `"n/a"` (or instead of a str, any number as previously)

**Review by sappelhoff — APPROVED** [review]

**Comment by mnoergaard** [comment]
Great, LGTM! Thanks @sappelhoff!

**Review by effigies — APPROVED** [review]
LGTM.

**Comment by effigies** [comment]
We should get an example that takes advantage of this so that it's tested.

**Pull request merged**
