### PR TITLE
issue-272: Shouldn't _rec- be excluded from "functional run/task identity"?  

### PR DESCRIPTION
**Pull request by suyashdb**
After adding `rec-` to the list where it shouldn't check for task name, there are other **warnings** as generated below:

`2: You should define 'EchoTime' for this file. If you don't provide this information field map correction will not be possible. (code: 6 - ECHO_TIME_NOT_DEFINED)
		/sub-Exp1s03/func/sub-Exp1s03_task-routelearning_rec-retest_run-02_bold.nii.gz

	3: You should define 'PhaseEncodingDirection' for this file. If you don't provide this information field map correction will not be possible. (code: 7 - PHASE_ENCODING_DIRECTION_NOT_DEFINED)
		/sub-Exp1s03/func/sub-Exp1s03_task-routelearning_rec-retest_run-02_bold.nii.gz

	4: You should define 'EffectiveEchoSpacing' for this file. If you don't provide this information field map correction will not be possible. (code: 8 - EFFECTIVE_ECHO_SPACING_NOT_DEFINED)
		/sub-Exp1s03/func/sub-Exp1s03_task-routelearning_rec-retest_run-02_bold.nii.gz

	5: You should define 'SliceTiming' for this file. If you don't provide this information slice time correction will not be possible. (code: 13 - SLICE_TIMING_NOT_DEFINED)
		/sub-Exp1s03/func/sub-Exp1s03_task-routelearning_rec-retest_run-02_bold.nii.gz

	6: Task scans should have a corresponding events.tsv file. If this is a resting state scan you can ignore this warning or rename the task to include the word "rest". (code: 25 - EVENTS_TSV_MISSING)
		/sub-Exp1s03/func/sub-Exp1s03_task-routelearning_rec-retest_run-02_bold.nii.gz`

I have added filter to exclude files with 'rec-' for above checks.

### CODE REVIEW

**Comment by chrisgorgo** [comment]
Closes #272.

**Comment by chrisgorgo** [comment]
Try modyfying https://github.com/INCF/bids-validator/blob/master/validators/nii.js#L271

Similar code has been implemented in grabbits https://github.com/grabbles/grabbit/blob/46d60a056fabf2eb1e68b56371a81213caaaaad9/grabbit/core.py#L333

**Comment by suyashdb** [comment]
for reconstructed task runs with k:v pair `_rec-`, all required metadata fields will be acquired from corresponding non reconstructed task .json. Similarly it will take care of `events.tsv` file too.   

@chrisfilo - Can you please review the PR?
I am not quite sure what has to be done with appveyor error above.

**Comment by chrisgorgo** [comment]
Step one: improve description of inheritance rule in the spec - https://docs.google.com/document/d/1HFUkAEE-pB-angVcYe6pf_-fVf4sCpOHKesUvfb8Grc/edit#heading=h.tfkd82hi8cl8

Step two: implement a generic traversal of directories and key/value pairs that goes beyond the "rec" key (see how it's implemented in grabbids).

**Comment by chrisgorgo** [comment]
Is this ready to review?

**Comment by suyashdb** [comment]
Not yet. I am yet to implement hierarchy rule.
Now that it's hierarchy rule is added to BIDS spec I will implement it in validator.

**Pull request closed without merging**
