### PR TITLE
add HED as optional column for other TSV files

### PR DESCRIPTION
**Pull request by sappelhoff**
- some steps towards: https://github.com/bids-standard/bids-validator/issues/1875

### CODE REVIEW

**Review by VisLab — COMMENTED** [review]
This looks good --- except I don't see `samples.tsv` and `samples.json` in this list. Thx!

**Comment by VisLab** [comment]
Also, I am wondering about the phenotype entry.  The phenotype is a
directory and the requirement is that phenotype/*.tsv should have a
participant_id. Thx

**Comment by sappelhoff** [comment]
> Also, I am wondering about the phenotype entry.  The phenotype is a directory and the requirement is that phenotype/*.tsv should have a participant_id. 

You are right about this. There is no `phenotype.tsv` ... only a `phenotype/<whatever-name>.tsv`.

I will merge this here and open a new issue.

**Comment by sappelhoff** [comment]
> This looks good --- except I don't see samples.tsv and samples.json in this list. Thx!

- fixes here: https://github.com/bids-standard/bids-validator/pull/1896

**Pull request merged**
