### PR TITLE
[WIP] Bep005 asl

### PR DESCRIPTION
**Pull request by rwblair**
corresponding examples: https://github.com/bids-standard/bids-examples/pull/225

### CODE REVIEW

**Comment by rwblair** [comment]
@marcocastellaro I added volume timing and fixed up some tests on your PR. I was unable to push it directly to your forked repo, so here are the changes if you want to merge them into your branch: 

https://github.com/bids-standard/bids-validator/tree/bep005_asl

**Comment by marcocastellaro** [comment]
> @marcocastellaro I added volume timing and fixed up some tests on your PR. I was unable to push it directly to your forked repo, so here are the changes if you want to merge them into your branch:
> 
> https://github.com/bids-standard/bids-validator/tree/bep005_asl

@rwblair  thank you!! I have pushed it back to my repo and will continue working on it. If you want I can add you in my repo, just in case we need your help!!

**Comment by rwblair** [comment]
@marcocastellaro @patsycle 
Looks like we are checking for LabelingDuration to be 0 if LabelingType is PASL, but the spec specifically states that LabelingDuration can only be used with CASL and PCASL. Should the spec or the validator be updated? (I'll take responsibility for updating the validator, I've got a few changes to this PR that I'm working on.)

**Comment by patsycle** [comment]
@rwblair Indeed, this is probably an older rule, which we missed in the final updates. Can you take it out? thanks

**Pull request merged**
