### PR TITLE
820 participant rows bugfix

### PR DESCRIPTION
**Pull request by exbotanical**
1. Disallows duplicate `participant_id`s in `participants.tsv`.
2. Requires `sub-` prefix on all `participant_id`s in `participants.tsv`.

NOTE: Per Ross' comment, the most recent commit preemptively resolves the merge conflict with #787 by including issue id no.125 as a shared entry among both branches.

### CODE REVIEW

**Comment by rwblair** [comment]
Issue code's might step on #787, its using 125 for the channel status column error.

**Review by david-nishi — DISMISSED** [review]

**Review by david-nishi — CHANGES_REQUESTED** [review]
Tests just need to be updated with new issue numbers. All else looks good!

**Comment by exbotanical** [comment]
> Tests just need to be updated with new issue numbers. All else looks good!

Missed those. Thanks, just pushed up :-)

**Review by sappelhoff — CHANGES_REQUESTED** [review]
meanwhile a part of this feature (`MISSING_SUB_PREFIX`) has been added in https://github.com/bids-standard/bids-validator/pull/1201

I think we don't have the `DUPLICATE_PARTICIPANT_ID` check from this PR in bids-validator yet, so that'd be a valuable addition.

However this PR needs to be rebased on `master`, and the current `MISSING_SUB_PREFIX` implementation needs to be removed.

**Pull request closed without merging**
